version: '3'

services:
  postgres:
    container_name: 'postgres-database'
    image: 'postgres:11.5-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=modulo11
